title: Collin Laney
description: The Resume of Collin Laney.
show_downloads: false
#google_analytics:
theme: jekyll-theme-modernist
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
